
-- Update Typebot
UPDATE "Typebot" 
SET "events" = '[{"id":"v0t2t6oopuj23vdb6tpowo5u","type":"start","outgoingEdgeId":"zw08tj9wol0q2q3i4372hv4r","graphCoordinates":{"x":0,"y":150}}]'::jsonb, 
    "edges" = '[{"id":"zw08tj9wol0q2q3i4372hv4r","from":{"eventId":"v0t2t6oopuj23vdb6tpowo5u"},"to":{"groupId":"exao9trxde9luucdfikqaszb"}},{"id":"jggg68fr9xmzk6htnyu2ib03","from":{"blockId":"lowpae24szrntg6o49hctatt"},"to":{"groupId":"ygzfwe3aqdfwfl2b02j3uwao"}},{"id":"qhd1wz9km1hc2zdy3che0cvx","from":{"blockId":"y3yykv4gdbpas96vgy2sn1iy"},"to":{"groupId":"nmotxvmc5wj9ptwsabshvosr"}}]'::jsonb, 
    "groups" = '[{"id":"exao9trxde9luucdfikqaszb","title":"👋 Bienvenida","blocks":[{"id":"jjwlh0ntrioy1rf7cjlz8m5v","type":"text","content":{"richText":[{"type":"p","children":[{"text":"¡Hola! Bienvenido a JGIS Publicidad. Soy Valentina Rios, tu agente virtual de ventas."}]}]}},{"id":"tlvtiec7iqz8ljfli63ivlug","type":"text","content":{"richText":[{"type":"p","children":[{"text":"¿Cómo te llamas?"}]}]}},{"id":"lowpae24szrntg6o49hctatt","type":"text input","options":{"labels":{"placeholder":"Escribe tu nombre..."},"variableId":"1kn6p3da9gbelnrs6mcfv8k8"},"outgoingEdgeId":"jggg68fr9xmzk6htnyu2ib03"}],"graphCoordinates":{"x":200,"y":100}},{"id":"ygzfwe3aqdfwfl2b02j3uwao","title":"📦 Selección de Producto","blocks":[{"id":"axv7ujz6pua8l5trnfje5ezw","type":"text","content":{"richText":[{"type":"p","children":[{"text":"Un gusto saludarte, "},{"bold":true,"text":"{{nombreClient}}"},{"text":". ¿Qué categoría te interesa cotizar hoy?"}]}]}},{"id":"u06iirfkdm45cwhw76s91y07","type":"choice input","items":[{"id":"w93feefeqhe1we2a5y86v7pl","content":"🏺 Tazas y Mugs"},{"id":"d3tz6xxx4qzl6fufc72qc5wm","content":"🧊 Tomatodos y Termos"},{"id":"8sdzpnojseg9c1i9bqcfd541","content":"🖊️ Lapiceros"},{"id":"zrjlsfrwgd0a2nch7uz4g5f7","content":"🎒 Mochilas y Bolsas"}],"options":{"variableId":"tucogdn160qgajucbkjbpntz"}},{"id":"f0a8eeuks52daqxevw4c0wqo","type":"text","content":{"richText":[{"type":"p","children":[{"text":"Escribe el nombre o palabra clave del producto que buscas (ej. \"taza con mango\" o \"tomatodo stanley\"):"}]}]}},{"id":"6h8wii89vh3fvb5wn4hg2o4j","type":"text input","options":{"labels":{"placeholder":"Buscar producto..."},"variableId":"9sxf5g6hvaz98vrgsf425icp"}},{"id":"evajo7t6310betxzo9026i7b","type":"text","content":{"richText":[{"type":"p","children":[{"text":"¿Qué cantidad de unidades deseas cotizar?"}]}]}},{"id":"y3yykv4gdbpas96vgy2sn1iy","type":"number input","options":{"labels":{"placeholder":"Ej. 50"},"variableId":"d8xxpsul4qn0ktqvicwd6r9x"},"outgoingEdgeId":"qhd1wz9km1hc2zdy3che0cvx"}],"graphCoordinates":{"x":550,"y":100}},{"id":"nmotxvmc5wj9ptwsabshvosr","title":"🔍 Búsqueda y Resultados","blocks":[{"id":"wb7k4o8xroumbd8kpg4qkbq6","type":"Webhook","options":{"isCustomBody":true,"responseMapping":[{"bodyPath":"message","variableId":"t7t3kuz4dnwc5tatsonvjuto"},{"bodyPath":"imageUrl","variableId":"869oi7estszj6f951dh643pm"}]},"webhookId":"wb7k4o8xroumbd8kpg4qkbq6"},{"id":"w9o4wpkclgn320jnwtztfp7i","type":"text","content":{"richText":[{"type":"p","children":[{"text":"{{respuestaBot}}"}]}]}},{"id":"idozms8tk47u0trg090qzrf4","type":"image","content":{"url":"{{imagenProducto}}"}}],"graphCoordinates":{"x":900,"y":100}}]'::jsonb 
WHERE "id" = 'o6jypntclntjiubkcf33vo50';

-- Update PublicTypebot
UPDATE "PublicTypebot" 
SET "events" = '[{"id":"v0t2t6oopuj23vdb6tpowo5u","type":"start","outgoingEdgeId":"zw08tj9wol0q2q3i4372hv4r","graphCoordinates":{"x":0,"y":150}}]'::jsonb, 
    "edges" = '[{"id":"zw08tj9wol0q2q3i4372hv4r","from":{"eventId":"v0t2t6oopuj23vdb6tpowo5u"},"to":{"groupId":"exao9trxde9luucdfikqaszb"}},{"id":"jggg68fr9xmzk6htnyu2ib03","from":{"blockId":"lowpae24szrntg6o49hctatt"},"to":{"groupId":"ygzfwe3aqdfwfl2b02j3uwao"}},{"id":"qhd1wz9km1hc2zdy3che0cvx","from":{"blockId":"y3yykv4gdbpas96vgy2sn1iy"},"to":{"groupId":"nmotxvmc5wj9ptwsabshvosr"}}]'::jsonb, 
    "groups" = '[{"id":"exao9trxde9luucdfikqaszb","title":"👋 Bienvenida","blocks":[{"id":"jjwlh0ntrioy1rf7cjlz8m5v","type":"text","content":{"richText":[{"type":"p","children":[{"text":"¡Hola! Bienvenido a JGIS Publicidad. Soy Valentina Rios, tu agente virtual de ventas."}]}]}},{"id":"tlvtiec7iqz8ljfli63ivlug","type":"text","content":{"richText":[{"type":"p","children":[{"text":"¿Cómo te llamas?"}]}]}},{"id":"lowpae24szrntg6o49hctatt","type":"text input","options":{"labels":{"placeholder":"Escribe tu nombre..."},"variableId":"1kn6p3da9gbelnrs6mcfv8k8"},"outgoingEdgeId":"jggg68fr9xmzk6htnyu2ib03"}],"graphCoordinates":{"x":200,"y":100}},{"id":"ygzfwe3aqdfwfl2b02j3uwao","title":"📦 Selección de Producto","blocks":[{"id":"axv7ujz6pua8l5trnfje5ezw","type":"text","content":{"richText":[{"type":"p","children":[{"text":"Un gusto saludarte, "},{"bold":true,"text":"{{nombreClient}}"},{"text":". ¿Qué categoría te interesa cotizar hoy?"}]}]}},{"id":"u06iirfkdm45cwhw76s91y07","type":"choice input","items":[{"id":"w93feefeqhe1we2a5y86v7pl","content":"🏺 Tazas y Mugs"},{"id":"d3tz6xxx4qzl6fufc72qc5wm","content":"🧊 Tomatodos y Termos"},{"id":"8sdzpnojseg9c1i9bqcfd541","content":"🖊️ Lapiceros"},{"id":"zrjlsfrwgd0a2nch7uz4g5f7","content":"🎒 Mochilas y Bolsas"}],"options":{"variableId":"tucogdn160qgajucbkjbpntz"}},{"id":"f0a8eeuks52daqxevw4c0wqo","type":"text","content":{"richText":[{"type":"p","children":[{"text":"Escribe el nombre o palabra clave del producto que buscas (ej. \"taza con mango\" o \"tomatodo stanley\"):"}]}]}},{"id":"6h8wii89vh3fvb5wn4hg2o4j","type":"text input","options":{"labels":{"placeholder":"Buscar producto..."},"variableId":"9sxf5g6hvaz98vrgsf425icp"}},{"id":"evajo7t6310betxzo9026i7b","type":"text","content":{"richText":[{"type":"p","children":[{"text":"¿Qué cantidad de unidades deseas cotizar?"}]}]}},{"id":"y3yykv4gdbpas96vgy2sn1iy","type":"number input","options":{"labels":{"placeholder":"Ej. 50"},"variableId":"d8xxpsul4qn0ktqvicwd6r9x"},"outgoingEdgeId":"qhd1wz9km1hc2zdy3che0cvx"}],"graphCoordinates":{"x":550,"y":100}},{"id":"nmotxvmc5wj9ptwsabshvosr","title":"🔍 Búsqueda y Resultados","blocks":[{"id":"wb7k4o8xroumbd8kpg4qkbq6","type":"Webhook","options":{"isCustomBody":true,"responseMapping":[{"bodyPath":"message","variableId":"t7t3kuz4dnwc5tatsonvjuto"},{"bodyPath":"imageUrl","variableId":"869oi7estszj6f951dh643pm"}]},"webhookId":"wb7k4o8xroumbd8kpg4qkbq6"},{"id":"w9o4wpkclgn320jnwtztfp7i","type":"text","content":{"richText":[{"type":"p","children":[{"text":"{{respuestaBot}}"}]}]}},{"id":"idozms8tk47u0trg090qzrf4","type":"image","content":{"url":"{{imagenProducto}}"}}],"graphCoordinates":{"x":900,"y":100}}]'::jsonb 
WHERE "typebotId" = 'o6jypntclntjiubkcf33vo50';

-- Ensure Webhook table contains connection settings for the HTTP Request
DELETE FROM "Webhook" WHERE "id" = 'wb7k4o8xroumbd8kpg4qkbq6';
INSERT INTO "Webhook" ("id", "url", "method", "queryParams", "headers", "body", "typebotId", "createdAt", "updatedAt")
VALUES (
  'wb7k4o8xroumbd8kpg4qkbq6',
  'http://host.docker.internal:3000/api/search',
  'POST',
  '[]'::jsonb,
  '[{"key": "Content-Type", "value": "application/json"}]'::jsonb,
  '{\n  "query": "{{busquedaProducto}}",\n  "quantity": {{cantidadSelected}},\n  "name": "{{nombreClient}}"\n}',
  'o6jypntclntjiubkcf33vo50',
  NOW(),
  NOW()
);
